//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optovaya_Basa
{
    using System;
    using System.Collections.Generic;
    
    public partial class TovarTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TovarTable()
        {
            this.Postavka = new HashSet<Postavka>();
        }
    
        public int IdTovara { get; set; }
        public int Kod { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public string UnitofMeasurement { get; set; }
        public int Cost { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postavka> Postavka { get; set; }
    }
}
